fix: add overflow behavior to integer division
substrait-io/substrait pull request #223
Opened 2022-06-09 17:20 UTC by westonpace

When working on https://github.com/apache/arrow/pull/13285 we noticed that there is no overflow behavior for division.  My first thought was that overflow is not possible on division but it turns out that there is one special case of overflow when the data type is signed integers.

For example, consider 8 bit signed integers.  The range is -128,127.  However, `-128 / -1 => 128` which is outside the range.  I'm not entirely sure what `SATURATE` would mean in this case but it seems it could mean 127 for the simplicity of having one set of overflow handling options for all the arithmetic.

2022-06-09 17:20 UTC, westonpace commented
CC @sanjibansg who discovered this discrepency

2022-06-09 18:43 UTC, jacques-n commented
Good catch. Do we need to add to decimal as well?

As a note, I don't see the the introduction of an optional argument to a function as a breaking change so consider this fix identification as a valid non-breaking change. (I think you went through this as well but want to call out explicitly.)

2022-07-04 00:08 UTC, jacques-n requested changes
Looking for same changes wrt to Decimal.

2022-07-05 20:48 UTC, westonpace commented
@jacques-n I'm not sure I understand.  Division for decimal already specifies overflow I think: https://github.com/substrait-io/substrait/blob/a79eb07a15cfa157e795f028a83f746967c98805/extensions/functions_arithmetic_decimal.yaml#L57

2022-07-12 16:00 UTC, merged