feat: Adding Variance Operator
substrait-io/substrait pull request #263
Opened 2022-07-26 04:10 UTC by vibhatha

This PR includes the addition of variance aggregation operator.

2022-07-26 09:35 UTC, jvanstraten requested changes
Same as for #257: not sure how to feel about the integer variants, and the floating point operations should use float rounding options rather than integer overflow options.

2022-07-26 09:41 UTC, vibhatha commented
> Same as for #257: not sure how to feel about the integer variants, and the floating point operations should use float rounding options rather than integer overflow options.

@jvanstraten I understand. We can hold until the decision is finalized.

2022-07-26 10:16 UTC, jvanstraten commented
YAML CI:

```
functions_arithmetic.yaml invalid
[
  {
    instancePath: '/aggregate_functions/4/impls/0',
    schemaPath: '#/properties/impls/items/required',
    keyword: 'required',
    params: { missingProperty: 'intermediate' },
    message: "must have required property 'intermediate'"
  }
]
```

@jacques-n I forgot which earlier PR this came up in. Could that have been one of the PRs you closed yesterday, maybe? I figured it'd be in main already.

2022-07-27 14:15 UTC, vibhatha commented
@jvanstraten I updated the PR.

2022-07-27 14:46 UTC, jvanstraten requested changes
LGTM aside from the above.

2022-07-27 14:46 UTC, jvanstraten commented on extensions/functions_arithmetic.yaml
> +        intermediate: "fp64?"
Looks like you might have deleted the wrong line here:

```suggestion
        nullability: DECLARED_OUTPUT
```

2022-07-27 14:56 UTC, vibhatha commented
@jvanstraten updated with the suggestion.

2022-07-27 17:10 UTC, jvanstraten commented
Same CI issues as #257, but LGTM otherwise.

2022-07-28 02:58 UTC, vibhatha commented
@jvanstraten updated the PR, there was a typo. Let's check the CIs once again. Sorry about this.

2022-07-28 14:03 UTC, vibhatha commented
@jvanstraten I squashed the commits to a single one. Let's see the CIs.

2022-07-28 15:46 UTC, jvanstraten approved these changes

2022-07-28 16:27 UTC, jacques-n commented
Hey @vibhatha , looks like other merges caused a merge conflict here. Can you rebase/fix?

Thanks!

2022-07-28 17:15 UTC, vibhatha commented
@jacques-n shall we go with this: https://github.com/substrait-io/substrait/pull/257 first and I will resolve conflicts after this.

2022-07-28 17:19 UTC, jacques-n commented
#257 is merged now.

2022-07-28 17:45 UTC, vibhatha commented
@jacques-n could you please check the content after rebase.

2022-07-28 17:47 UTC, merged