feat: add hyperbolic functions
substrait-io/substrait pull request #290
Opened 2022-08-17 09:17 UTC by thisisnic

This PR adds hyperbolic functions

2022-08-17 14:05 UTC, jvanstraten requested changes
Uh, hm. I guess I didn't catch this in #241, but it should be fp32 -> fp32 and fp64 -> fp64. Unless you're building huge lookup tables (which may or may not be feasible for fp32, not so much for fp64) I see zero reason to have an fp32 -> fp64 variant from a computational perspective, and it goes against #251. Can you change the new functions to fp32 -> fp32? I'll submit a patch to weed out inconsistencies between all the new functions in general (and at some point to codify #251, since there have been no objections) later.

2022-08-17 14:33 UTC, thisisnic commented
> Uh, hm. I guess I didn't catch this in #241, but it should be fp32 -> fp32 and fp64 -> fp64. Unless you're building huge lookup tables (which may or may not be feasible for fp32, not so much for fp64) I see zero reason to have an fp32 -> fp64 variant from a computational perspective, and it goes against #251. Can you change the new functions to fp32 -> fp32? I'll submit a patch to weed out inconsistencies between all the new functions in general (and at some point to codify #251, since there have been no objections) later.

Good catch, I've updated them in this PR now!

2022-08-17 15:03 UTC, jvanstraten approved these changes
Thanks, LGTM now.

2022-09-02 13:32 UTC, jvanstraten approved these changes

2022-09-02 13:32 UTC, merged