feat: add regexp_match_substring, regexp_strpos, and regexp_count_sub…
substrait-io/substrait pull request #293
Opened 2022-08-17 23:06 UTC by richtia

PR to add remaining regexp string functions

2022-08-18 07:40 UTC, jvanstraten approved these changes
LGTM

2022-09-02 13:35 UTC, jvanstraten requested changes
Sorry for the review change, but as discussed elsewhere, we should probably add `CASE_INSENSITIVE_ASCII` for consistency with the case conversion functions.

2022-09-02 16:09 UTC, richtia commented
> Sorry for the review change, but as discussed elsewhere, we should probably add `CASE_INSENSITIVE_ASCII` for consistency with the case conversion functions.

Updated!

2022-09-02 17:02 UTC, jvanstraten approved these changes

2022-09-02 17:02 UTC, merged