fix: Adding missing arg names for aggregate yaml
substrait-io/substrait pull request #316
Opened 2022-09-08 11:24 UTC by vibhatha

This PR adds the missing argument names in `functions_aggregate_approx.yaml` and `functions_aggregate_generic.yaml`.

2022-09-08 14:57 UTC, jvanstraten commented
The sole argument there would just be named `overflow`. The intended behavior of the function is to count all records when aggregating (so there's no need to reference a field) if that's what you were wondering about, but I don't really like that special case either if that's what you mean... nor do I like those functions having the same name, which is something I hadn't really considered as an option yet. But I guess that's legal because the compound names are different, so... more work for the validator :/

2022-09-08 16:06 UTC, vibhatha commented
> The sole argument there would just be named `overflow`. The intended behavior of the function is to count all records when aggregating (so there's no need to reference a field) if that's what you were wondering about, but I don't really like that special case either if that's what you mean... nor do I like those functions having the same name, which is something I hadn't really considered as an option yet. But I guess that's legal because the compound names are different, so... more work for the validator :/

So we could have the following for the unnamed count function?

```YAML
- name: "count"
    description: "Count a set of records (not field referenced)"
    impls:
      - args:
          - name: overflow
          - options: [SILENT, SATURATE, ERROR]
            required: false
        nullability: DECLARED_OUTPUT
        decomposable: MANY
        intermediate: i64
        return: i64
```

2022-09-08 17:23 UTC, jvanstraten commented
Uh, more or less, but without the `-` before `options`.

2022-09-09 00:29 UTC, vibhatha commented
@jvanstraten updated the PR.

2022-09-12 08:15 UTC, jvanstraten requested changes

2022-09-12 08:15 UTC, jvanstraten commented on extensions/functions_aggregate_generic.yaml
> +          - name: x
In this case, it should actually be named `overflow`.

```suggestion
          - name: overflow
```

2022-09-12 08:15 UTC, jvanstraten commented on extensions/functions_aggregate_generic.yaml
>            - options: [SILENT, SATURATE, ERROR]
The `overflow` name is also missing here.

2022-09-13 01:26 UTC, vibhatha commented
@jvanstraten updated the PR.

2022-09-14 09:38 UTC, jvanstraten approved these changes

2022-09-14 09:38 UTC, merged