feat: Adding any_value aggregate function WIP
substrait-io/substrait pull request #321
Opened 2022-09-08 14:08 UTC by vibhatha

This PR is work in progress to add `any_value` aggregate function.

2022-09-08 15:29 UTC, jvanstraten commented on extensions/functions_arithmetic.yaml
> +      is not necessary to be included in the GROUP BY clause.
I don't think this applies to Substrait, so I think it can be removed.

2022-09-08 15:29 UTC, jvanstraten commented on extensions/functions_arithmetic.yaml
> +      When the expression is NULL, it returns NULL for all values in the group.
I'm not sure what's going on here. I would expect something like "If the input is empty, this returns null." and that's it, I don't see any special cases beyond that.

2022-09-08 15:58 UTC, vibhatha commented
@jvanstraten I updated the PR.

2022-09-08 17:18 UTC, jvanstraten commented
Sorry, I don't know why I didn't notice this before, but there's no reason for this to be limited to numeric types. It can just be `any_value(T) -> T`. It should also be in the file for generic aggregates.

2022-09-09 00:26 UTC, vibhatha commented
@jvanstraten updated the PR.

2022-09-12 08:13 UTC, jvanstraten requested changes

2022-09-12 08:13 UTC, jvanstraten commented on extensions/functions_arithmetic.yaml
> +        return: fp64?
This is completely covered by the `f(any) -> any?` variant, and it isn't really an arithmetic function to begin with. So why is this still here?

2022-09-19 06:23 UTC, vibhatha commented
@jvanstraten updated the PR. Is it okay now?

2022-09-19 13:20 UTC, jvanstraten approved these changes
Yeah, LGTM now, I think.

2022-09-19 13:21 UTC, merged